[project]
name = "adk-eval-challenge-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk[eval]>=2.10.0",
    "google-auth>=2.58.1",
    "google-cloud-bigquery>=3.45.2",
    "google-cloud-dataplex>=2.20.0",
    "google-cloud-logging>=3.16.3",
]

[project.scripts]
adk-eval-challenge-lab = "adk_eval_challenge_lab:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
